Practica1
umoqnier/cl-2024-2-lab pull request #18
Opened 2024-03-05 06:14 UTC by saul-code

Ejercicios 1 2 y 3

2024-03-05 06:17 UTC, saul-code commented
Perdón por la entrega tardia, me costo subirlo a git y me costo entender el codigo.

2024-03-25 04:30 UTC, umoqnier commented
A tiempo :timer_clock:

2024-04-25 22:02 UTC, umoqnier requested changes
Por favor quita todo lo que viene dentro de la carpeta `myenv/`. Eso no debería subirse al repo

2024-05-21 01:45 UTC, umoqnier approved these changes
Funciona bien y se realiza lo que se pide en la práctica

**calificación: 10**

2024-05-21 01:45 UTC, umoqnier commented on practices/Fili/practica1/Parte1y2.py
> +    return dataset.get(word.lower(), "NOT FOUND").split(", ")
Esta función es reimplementada más abajo, conviene mas bien eliminar esta ya que no se usa más

2024-05-21 01:56 UTC, merged