FEAT: Directorio y ReadMe de Ahexo (Axel)
umoqnier/cl-2024-2-lab pull request #2
Opened 2024-02-15 23:00 UTC by Ahexo

El título lo dice todo.
Hice otro PR porque en el anterior no hice la rama nueva ni el fichero /practica0 :P

2024-02-20 01:24 UTC, umoqnier requested changes
Cambios

2024-02-20 01:24 UTC, umoqnier commented on practices/Ahexo/practica0/README.md
El fichero no es necesario. El readme puede quedar al nivel de la raíz. Ej `practices/Ahexo/README.md` Corrigelo si gustas si no indicame para dejarlo asi

2024-02-22 18:24 UTC, Ahexo reviewed
Va, he eliminado el fichero.

2024-02-22 20:40 UTC, umoqnier approved these changes

2024-02-22 20:40 UTC, umoqnier commented on practices/Ahexo/README.md
> +- Pasear y jugar con mis perros. Tengo tres: Pánfilo, Dinky y Emilia.
<3

2024-02-22 20:40 UTC, umoqnier commented on practices/Ahexo/README.md
> +- Participo activamente en el grupo de investigación de [Filosofía de la Computación](https://philcomp.org/) de la Facultad. El año pasado organizamos un simposio en el que presenté un trabajo sobre
:eyes:

2024-02-22 20:40 UTC, merged