Practica0
umoqnier/cl-2024-2-lab pull request #9
Opened 2024-02-28 20:58 UTC by Super-Gabriel

Radme agregado.

2024-02-29 03:12 UTC, umoqnier requested changes
Dejaste un archivo ahí vacío. Quitalo por favors

2024-02-29 03:12 UTC, umoqnier commented on practices/Super-Gabriel/README.md~
keseso? Borralo O: parece un archivo vacío

2024-02-29 03:12 UTC, umoqnier commented on practices/Super-Gabriel/README.md
> +- Jugar ajedrez
:100:  noice

2024-03-01 05:55 UTC, Super-Gabriel commented
Archivo eliminado.

2024-03-04 00:31 UTC, Super-Gabriel commented
practica01 agregada, desde la linea 320 están los ejercicios

2024-03-04 00:32 UTC, closed without merging

2024-03-04 00:39 UTC, umoqnier commented
Recuerda que debe hacer las prácticas una en cada rama. Este pr esta cerrado. Pro favor entrega la práctica en la rama correspondiente. Ej: p1